language: rust
rust:
 - stable
cache: cargo
os:
  - linux
  - osx
  - windows
script:
 - cargo build --verbose
 - cargo test --verbose
matrix:
  allow_failures:
    - rust:
      - nightly
  fast_finish: true
